config/routes.rb
Rails.application.routes.draw do
# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

#管理者側ルーディング
namespace :admin do
  root to: "homes#top"
  resources :posts, only: [:index, :show, :destroy, :edit, :update] do
    resources :post_comments, only: [:destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
  end
  get '/search', to: 'searches#search'
end

# 顧客用
# URL /users/sign_in ...
  devise_for :users,  skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 顧客側ルーディング
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy, :update, :edit]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      member do
        get :favorites
      end
    end
    get '/search', to: 'searches#search'
    get 'search_tag', to: 'posts#search_tag'
  end

# ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }

  enum role: { general: 'public', admin: 'admin' }

  def get_profile_image(width, height)
    if profile_image.attached?
      profile_image.variant(resize_to_limit: [width, height]).processed
    else
      'no_image.jpg'
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!
    def show
      @user = User.find(params[:id])
      @posts = @user.posts
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      else
        render :edit
      end
    end
  
    def destroy
      user = User.find(params[:id])
      user.destroy
      redirect_to admin_users_path, notice: "ユーザーを退会させました。"
    end
  
    def index
      @users = User.all
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :profile_image, :email)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_index.html.erb
<div class="container mt-4 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <% if users.present? %>
        <% users.each do |user| %>
          <div class="mb-3 p-3 border rounded shadow-sm bg-white">
            <div class="d-flex align-items-center mb-2">
              <% if user.present? && user.get_profile_image(50, 50) %>
                <% image_path = user.get_profile_image(50, 50) %>
                <%= image_tag image_path, class: "rounded-circle me-3", size: "50x50" %>
              <% else %>
                <%= image_tag 'no_image.jpg', class: "rounded-circle me-3", size: "50x50" %>
              <% end %>

              <h5 class="mb-0"><%= user.name %></h5>
              
            </div>

            <div class="text-end mt-2">
              <%= link_to '詳細へ', admin_user_path(user.id), class: "btn btn-sm btn-outline-primary" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="text-center text-muted">該当するユーザーは見つかりませんでした</p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= render 'index', users: @users %>

app/views/admin/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-12 col-sm-10 col-md-3 mx-auto shadow-lg px-0 my-5 text-center">
      <% profile_image_path = @user.get_profile_image(100, 100) %>
      <%= image_tag profile_image_path, class: "img-fluid rounded-circle mt-4", size: "100x100" %>
      <h3 class="mb-3 mt-2"><%= @user.name %></h3>
      <%= link_to "退会", admin_user_path(@user.id), method: :delete, data: { confirm: "本当に退会させますか？" }, class: "btn btn-danger ms-3 mb-4" %>
      <% if @user == current_user %>
        <p><%= link_to "プロフィール編集", edit_admin_user_path(@user), class: "btn btn-outline-primary" %></p>
      <% end %>
    </div>
  </div>

  <% if @posts.present? %>
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-12 col-md-4 mb-4">
          <div class="p-3 border rounded h-100 d-flex flex-column shadow">
            <p>芸人名 : <%= truncate(post.comedian_name) %></p>
            <p>ネタ : <%= truncate(post.title) %></p>
            <p>感想 : <%= simple_format(truncate(post.body, length: 150)) %></p>
            <p><%= render "layouts/star", post: post %></p>
            <div class="d-flex justify-content-start align-items-center text-muted small mb-3">
              <span><%= "#{post.post_comments.count} コメント" %></span>
              <span class="mx-2"> | </span>
              <span><%= render "layouts/btn", post: post %></span>
              <span class="mx-2"> | </span>
              <span>
                <% post.tags.each_with_index do |tag, i| %>
                  <%= link_to tag.name, admin_search_path(content: tag.name, model: "tag", method: "perfect") %><%= ',' unless i == post.tags.size - 1 %>
                <% end %>
              </span>
            </div>
            <%= link_to '詳細へ', admin_post_path(post.id), class: "btn btn-sm btn-outline-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-center text-muted">投稿がまだありません</p>
  <% end %>
</div>