config/routes.rb
Rails.application.routes.draw do
# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

#管理者側ルーディング
namespace :admin do
  root to: "homes#top"
  resources :posts, only: [:index, :show, :destroy, :edit, :update] do
    resources :post_comments, only: [:destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
  end
  get '/search', to: 'searches#search'
end

# 顧客用
# URL /users/sign_in ...
  devise_for :users,  skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# 顧客側ルーディング
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy, :update, :edit]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      member do
        get :favorites
      end
    end
    get '/search', to: 'searches#search'
    get 'search_tag', to: 'posts#search_tag'
  end

# ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :comedian_name, presence: true
    has_one_attached :image  
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :favorites, dependent: :destroy
    attr_accessor :tag_name
    scope :latest, -> {order(created_at: :desc)}
    scope :old, -> {order(created_at: :asc)}
    scope :rate, -> {order(rate: :desc)}
    scope :favorites_count, -> {
      left_joins(:favorites)
      .group(:id)
      .order('COUNT(favorites.id) DESC')
    }


    def save_tags(savepost_tags)
      current_tags = self.tags.pluck(:name) unless self.tags.nil?
      old_tags = current_tags - savepost_tags
      new_tags = savepost_tags - current_tags

      old_tags.each do |old_name|
        self.tags.delete Tag.find_by(name:old_name)
      end
      
      new_tags.each do |new_name|
        tag = Tag.find_or_create_by(name: new_name.strip)
        self.tags << tag unless self.tags.include?(tag)
      end
    end

    def favorited_by?(user)
      return false if user.nil?
      favorites.where(user_id: user.id).exists?
    end

    def self.search_for(content, method)
      if method == 'perfect'
        where('comedian_name = :content OR title = :content OR body = :content', content: content)
      elsif method == 'forward'
        where('comedian_name LIKE :content OR title LIKE :content OR body LIKE :content', content: "#{content}%")
      elsif method == 'backward'
        where('comedian_name LIKE :content OR title LIKE :content OR body LIKE :content', content: "%#{content}")
      else
        where('comedian_name LIKE :content OR title LIKE :content OR body LIKE :content', content: "%#{content}%")
      end
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

    belongs_to :user
    belongs_to :post

    validates :comment, presence: true

end

app/models/post_tag.rb
class PostTag < ApplicationRecord
    belongs_to :post
    belongs_to :tag
    validates :post_id, presence: true
    validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
    has_many :posts,through: :post_tags
    
    validates :name, uniqueness: true, presence: true
    scope :merge_books, -> (tags){ }
  
    def self.search_posts_for(content, method)
      
      if method == 'perfect'
        tags = Tag.where(name: content)
      elsif method == 'forward'
        tags = Tag.where('name LIKE ?', content + '%')
      elsif method == 'backward'
        tags = Tag.where('name LIKE ?', '%' + content)
      else
        tags = Tag.where('name LIKE ?', '%' + content + '%')
      end
      
      Post.joins(:tags).where(tags: { id: tags.pluck(:id) }).distinct
      
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }

  enum role: { general: 'public', admin: 'admin' }

  def get_profile_image(width, height)
    if profile_image.attached?
      profile_image.variant(resize_to_limit: [width, height]).processed
    else
      'no_image.jpg'
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
	
    def after_sign_in_path_for(resource)
      if resource.is_a?(Admin)
        admin_posts_path
      else
        posts_path
      end
    end

    def after_sign_out_path_for(resource)
        user_session_path
    end

    protected
	
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_about.html.erb
<div class="col-md-6 mx-auto mt-5 text-center">
  <h1>What about <strong>ネタレコ</strong>  ??</h1>
  <p>ネタレコは自分の好きなネタをレコードすることができるサービスです。</p>
  <p>どんどんレコメンドして、笑いの輪を広げていきましょう！</p>
</div>

app/views/layouts/_btn.html.erb
<% if user_signed_in? && !current_user.guest_user? && !current_user.admin? %>
  <% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post), method: :delete, style: "color: red;" do %>
      <i class="fa-solid fa-face-grin-squint-tears" aria-hidden="true"></i>
      <%= post.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post), method: :post do %>
      <i class="fa-regular fa-face-grin-squint" aria-hidden="true"></i>
      <%= post.favorites.count %>
    <% end %>
  <% end %>
<% else %>
  <span>
    <i class="fa-regular fa-face-grin-squint" aria-hidden="true"></i>
    <%= post.favorites.count %>
  </span>
<% end %>

app/views/layouts/_edit.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<div class="container">
  <div class="d-flex justify-content-end py-2">
    <% if admin_signed_in? %>
      <%= form_with url: admin_search_path, method: :get, local: true, class: "form-inline" do |f| %>
        <%= f.text_field :content, placeholder: 'キーワードを入力', class: "form-control mr-2" %>
        <%= f.select :model, options_for_select({ "ユーザー" => "user", "キーワード" => "post", "タグ" => "tag" }), {}, class: "form-control mr-2" %>
        <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }), {}, class: "form-control mr-2" %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>
    <% elsif user_signed_in? %>
      <%= form_with url: search_path, method: :get, local: true, class: "form-inline" do |f| %>
        <%= f.text_field :content, placeholder: 'キーワードを入力', class: "form-control mr-2" %>
        <%= f.select :model, options_for_select({ "ユーザー" => "user", "キーワード" => "post", "タグ" => "tag" }), {}, class: "form-control mr-2" %>
        <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }), {}, class: "form-control mr-2" %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_header_admin.html.erb
<body class="d-flex flex-column vh-100">
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/about"><%= image_tag('icon.jpg', size: "180x70") %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <li class="px-4">
          <%= link_to admin_posts_path do %>
            <i class="fa-solid fa-hand-holding-hand"></i> 投稿一覧
          <% end %>
        </li>
        <li class="px-4">
          <%= link_to admin_users_path do %>
            <i class="fa-solid fa-users"></i> ユーザーリスト
          <% end %>
        </li>
        <li class="px-4">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa-solid fa-arrow-right-from-bracket me-1"></i> ログアウト
          <% end %>
        </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
</body>

app/views/layouts/_header_public.html.erb
<body class="d-flex flex-column vh-100">
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/about"><%= image_tag('icon.jpg', size: "180x70") %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <li class="px-4">
          <%= link_to new_post_path do %>
            <i class="fa-solid fa-hand-holding-heart"></i> 新規投稿
          <% end %>
        </li>
        <li class="px-4">
          <%= link_to posts_path do %>
            <i class="fa-solid fa-hand-holding-hand"></i> 投稿一覧
          <% end %>
        </li>
        <li class="px-4">
          <%= link_to user_path(current_user.id) do %>
            <i class="fa-solid fa-user"></i> マイページ
          <% end %>
        </li>
        <li class="px-4">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa-solid fa-arrow-right-from-bracket me-1"></i> ログアウト
          <% end %>
        </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
</body>

app/views/layouts/_index.html.erb
<div class="container mt-4 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-9">

    <!--ソート機能-->
      <%= link_to '新しい順', admin_search_path(params.permit(:content, :model, :method).merge(latest: "true")) %>
      | <%= link_to '古い順', admin_search_path(params.permit(:content, :model, :method).merge(old: "true")) %>
      | <%= link_to '評価の高い順', admin_search_path(params.permit(:content, :model, :method).merge(rate: "true")) %>
      | <%= link_to 'いいねの多い順', admin_search_path(params.permit(:content, :model, :method).merge(favorites_count: "true")) %>
    <!--ソート機能ここまで-->

        <% if posts.present? %>
            <% posts.each do |post| %>
                <div class="mb-3 p-3 border rounded shadow-sm">
                    <div class="d-flex align-items-center mb-2">
                        <% if post.user %>
                          <% image_path = post.user.get_profile_image(50, 50) %>
                          <%= image_tag image_path, class: "rounded-circle me-3", size: "50x50" %>
                        <% else %>
                          <%= image_tag 'no_image.jpg', class: "rounded-circle me-3", size: "50x50" %>
                        <% end %>
                            <h5 class="mb-2"><%= post.comedian_name %></h5>
                    </div>
                    <p class="mb-0">ネタ：<%= post.title %></p>
                    <p class="mb-2"><%= simple_format(post.body) %></p>
                    <p><%= render "layouts/star", post: post %></p>
                        <div class="d-flex justify-content-start align-items-center text-muted small">
                            <span class="me-3">
                                <%= post.user.present? ? post.user.name : '未登録ユーザー' %>
                            </span>
                            <span class="mx-2"> | </span>
                            <span>
                            <%= "#{post.post_comments.count} コメント" %>
                            </span>
                            <span class="mx-2"> | </span>

                            <!--ファボ-->
                            <% if user_signed_in? && !current_user.guest_user? %>
                              <%= link_to post_favorites_path(post), method: :post, remote: true do %>
                                <span><%= render "layouts/btn", post: post %></span>
                              <% end %>
                            <% else %>
                              <span>
                                <%= render "layouts/btn", post: post %>
                              </span>
                            <% end %>
                          <!--ここまで-->
                            <span class="mx-2"> | </span>
                            <span>
                            <% post.tags.each_with_index do |tag, i| %>
                             <%= link_to tag.name, admin_search_path(content: tag.name, model: "tag", method: "perfect") %><%= ',' unless i == post.tags.size - 1 %>
                            <% end %>
                            </span>
                        </div>
                        <div class="text-end mt-2">
                            <%= link_to '詳細へ', admin_post_path(post.id), class: "btn btn-sm btn-outline-primary" %>
                        </div>
                </div>
            <% end %>
        <% else %>
            <p class="text-center text-muted">該当する投稿は見つかりませんでした</p>
        <% end %>      
    </div>
  </div>
</div>

app/views/layouts/_star.html.erb
<div id="rate_<%= post.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#rate_<%= post.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= post.rate %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/layouts/_tag_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.hidden_field :model, :value => "tag"  %>
    <%= f.hidden_field :method, :value => "perfect" %>
    <%= f.submit 'タグ検索' %>
  <% end %>
<% end %>

app/views/layouts/_top.html.erb
<div class="col-md-6 mx-auto mt-5 text-center">
  <h1>Welcome to <strong>ネタレコ</strong>  !!</h1>
  <p>ネタレコは自分の好きなネタをレコードすることができるサービスです。</p>
  <p>どんどんレコメンドして、笑いの輪を広げていきましょう！</p>
  <div class="d-flex justify-content-center mb-3">
    <a class="btn btn-success mr-3" href="/users/sign_up">新規登録</a>
    <a class="btn btn-info" href="/users/sign_in">ログイン</a>
  </div>
  <li class="px-4" style="list-style:none;">
    <%= form_with url: users_guest_sign_in_path, method: :post, local: true do %>
      <%= submit_tag "ゲストログイン", class: "btn btn-secondary" %>
    <% end %>
  </li>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netareco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/161e2fa7d8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    
    
    <% if admin_signed_in? %>
      <%= render 'layouts/header_admin' %>
    <% elsif user_signed_in? %>
      <%= render 'layouts/header_public' %>
    <% else %>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('icon.jpg', size: "180x70") %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="px-4">
              <%= link_to new_user_registration_path do %>
                <i class="fa-regular fa-address-card"></i> 新規登録
              <% end %>
            </li>
            <li class="px-4">
              <%= link_to new_user_session_path do %>
                <i class="fa-solid fa-arrow-right-to-bracket"></i> ログイン
              <% end %>
            </li>
            <li class="px-4">
              <%= link_to users_guest_sign_in_path, method: :post do %>
                <i class="fa-solid fa-person-walking-arrow-right"></i> ゲストログイン
              <% end %>
            </li>
            <li class="px-4">
              <%= link_to about_path do %>
                <i class="fa-solid fa-circle-info"></i> About
              <% end %>
            </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <% end %>

  <main class="mb-auto">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
      <div class="justify-content-center mb-2">
        <%= render 'layouts/form' %>
      <%= yield %>
      </div>
  </main>
  
  <!--フッター-->
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%= image_tag('icon.jpg', size: "180x70") %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-4 mb-3">SHARE YOUR LAUGHS.　FIND YOUR FUN.</h6>
          </div>
        </div>
      </div>
    </footer>
  <!--ここまで-->

  </body>
</html>